// <auto-generated />
using TimeHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GSK_TimeAssistant_Data.Migrations
{
    [DbContext(typeof(TimeHelperDataContext))]
    [Migration("20201216120436_seed-association-more")]
    partial class seedassociationmore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TimeHelper.Data.Models.Association", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Criteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssociationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Association");

                    b.HasData(
                        new
                        {
                            AssociationId = -1,
                            Criteria = "xtc",
                            ProjectId = -1,
                            Type = 0,
                            UserId = "nick@nikkh.net"
                        },
                        new
                        {
                            AssociationId = -2,
                            Criteria = "AQ37",
                            ProjectId = -1,
                            Type = 1,
                            UserId = "nick@nikkh.net"
                        },
                        new
                        {
                            AssociationId = -3,
                            Criteria = "armageddon",
                            ProjectId = -2,
                            Type = 0,
                            UserId = "keith2@nikkh.net"
                        },
                        new
                        {
                            AssociationId = -4,
                            Criteria = "AGN404",
                            ProjectId = -2,
                            Type = 1,
                            UserId = "keith2@nikkh.net"
                        },
                        new
                        {
                            AssociationId = -5,
                            Criteria = "wolverine",
                            ProjectId = -2,
                            Type = 0,
                            UserId = "nick@nikkh.net"
                        });
                });

            modelBuilder.Entity("TimeHelper.Data.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = -1,
                            Description = "Project Aquarius",
                            Name = "Aquarius"
                        },
                        new
                        {
                            ProjectId = -2,
                            Description = "Project Armageddon",
                            Name = "Armageddon"
                        });
                });

            modelBuilder.Entity("TimeHelper.Data.Models.Association", b =>
                {
                    b.HasOne("TimeHelper.Data.Models.Project", "Project")
                        .WithMany("Associations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimeHelper.Data.Models.Project", b =>
                {
                    b.Navigation("Associations");
                });
#pragma warning restore 612, 618
        }
    }
}
