name: Build Time Helper Infrastructure

on: 
  workflow_dispatch:
    inputs:
      alias:
        description: 'Application alias'     
        required: true
        default: 'aaa'
      location:
        description: 'Location'     
        required: true
        default: 'uksouth'
      instance:
        description: 'Instance Name'     
        required: true
        default: 'Lucky_Strike'
      pendingDelete:
        description: 'pending delete?'     
        required: true
        default: 'true'
       
env:
   AAD_APICLIENTID : ${{ secrets.AAD_API_CLIENT_ID }}
   AAD_APICLIENTSECRET : ${{ secrets.AAD_API_CLIENT_SECRET }}  
   AAD_WEBCLIENTID : ${{ secrets.AAD_WEB_CLIENT_ID }}
   AAD_WEBCLIENTSECRET : ${{ secrets.AAD_WEB_CLIENT_SECRET }}
   AAD_DOMAIN: ${{ secrets.AAD_DOMAIN }}
   AAD_TENANTID: ${{ secrets.AAD_TENANTID }}
   
   DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
   TIMEHELPER_API_SCOPE: ${{ secrets.TIMEHELPER_API_SCOPE }} 
   DB_ADMIN_USER: dbadminuser
   
   SWAGGER_CONTACT_URL: https://github.com/nikkh
   SWAGGER_CONTACT_NAME: Nick Hill 
   SWAGGER_CONTACT_EMAIL: 'nick dot hill at microsoft dot com'
   
   TIMEHELPER_ALIAS: ${{ github.event.inputs.alias }}timehelper
   TIMEHELPER_LOCATION: ${{ github.event.inputs.location }}
   TIMEHELPER_INSTANCE: ${{ github.event.inputs.instance }}
   PENDING_DELETE: ${{ github.event.inputs.pendingDelete }}
   OUTPUT_LOG_NAME: "deployment-log.html"  

jobs:
  job1:
    name: Create TimeHelper Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        id: step1
                    
      - name: Login to Azure
        uses: azure/login@v1
        id: step2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
   
      - name: Run Deployment Scripts
        id: step3
        run: |
                chmod +x deployment-scripts/deploy_infrastructure.sh
                deployment-scripts/deploy_infrastructure.sh
           
  job2:
    name: Api Deployment
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - id: step1
      name: Initiate Api Deployment
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: TimeHelper Api Deployment
        token: ${{ secrets.PAT }}
        inputs: '{ "timehelper_alias": "${{ env.TIMEHELPER_ALIAS }}" }'  
  
  job3:
    name: Site Deployment
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - id: step1
      name: Initiate Web Site Deployment
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: TimeHelper Web Site Deployment
        token: ${{ secrets.PAT }}
        inputs: '{ "timehelper_alias": "${{ env.TIMEHELPER_ALIAS }}" }'  
  
  job4:
    name: Client Deployment
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
    - id: step1
      name: Initiate Client Deployment
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: TimeHelper Client Deployment
        token: ${{ secrets.PAT }}
        inputs: '{ "timehelper_alias": "${{ env.TIMEHELPER_ALIAS }}" }'  
  
